name = "RankWidthSolver"
uuid = "211beeaa-8dfe-42af-805a-8be62ccfa100"
version = "1.0.0-DEV"
authors = ["Huai-Ming Yu<hmyuus@gmail.com>"]

[deps]
AbstractTrees = "1520ce14-60c1-5f80-bbc7-55ef81b5835c"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
OMEinsumContractionOrders = "6f22d1fd-8eed-4bb7-9776-e7d684900715"

[compat]
AbstractTrees = "0.4.5"
Graphs = "1.13.2"
OMEinsumContractionOrders = "1.2.3"
julia = "1.12"
